import{AccountMain} from"./account";

export const ACCOUNTSAMP:AccountMain[]=[
    {
        id: 1,
        fname:'Kile',
        lname:'Avera',
        email:'Kile@gmail.com',
        mobile:'094631878316',
        gender:'Female',
        marital:'Married',
        dateb:'11/19/1985',
        imgPath: 'assets/account1.jpg',
    },
    {
        id: 2,
        fname:'Renatz',
        lname:'Bigboy',
        email:'Renatz@gmail.com',
        mobile:'094621471316',
        gender:'Male',
        marital:'Single',
        dateb:'01/19/2003',
        imgPath: 'assets/account2.jpg',
    },
    {
        id: 3,
        fname:'Chris',
        lname:'Ganda',
        email:'ChrisGanda@gmail.com',
        mobile:'094631878316',
        gender:'Female',
        marital:'Single',
        dateb:'08/30/2003',
        imgPath: 'assets/account3.JPG',
    },
    {
        id: 4,
        fname:'Jan',
        lname:'Leigh',
        email:'Lei@gmail.com',
        mobile:'094631878316',
        gender:'Male',
        marital:'Single',
        dateb:'01/1/1985',
        imgPath: 'assets/account4.jpg',
    },
    {
        id: 5,
        fname:'Chrysa',
        lname:'Gali',
        email:'chrysa@gmail.com',
        mobile:'094631878316',
        gender:'Female',
        marital:'Married',
        dateb:'04/02/1995',
        imgPath: 'assets/account5.jpg',
    },
    {
        id: 6,
        fname:'Angge',
        lname:'Pangilinan',
        email:'Angge@gmail.com',
        mobile:'094631878316',
        gender:'Female',
        marital:'Single',
        dateb:'04/02/1995',
        imgPath: 'assets/account6.jpg',
    },
    {
        id: 7,
        fname:'Zeus',
        lname:'Laureta',
        email:'zeus@gmail.com',
        mobile:'094631878316',
        gender:'Male',
        marital:'Married',
        dateb:'04/02/1995',
        imgPath: 'assets/account7.jpg',
    },
    {
        id: 8,
        fname:'Megs',
        lname:'Vlas',
        email:'Megs@gmail.com',
        mobile:'094631878316',
        gender:'Female',
        marital:'Married',
        dateb:'04/02/1995',
        imgPath: 'assets/account8.jpg',
    }
]