import { Redvelvet } from "./redvelvet";

export const REDVELVET: Redvelvet[]=[

    {   id: 29,
        name: "Bae Ju-hyeon",
        stage: "IRENE",
        position: "Leader, Main Rapper, Lead Dancer, Vocalist, Visual, Center",
        bday: "March 29, 1991",
        nationality: "Korean",
        height: "1.58 m (5'1)",
        zodiac: "Aries ♈︎",
        img: "irene1.jpg",
        img2: "irene2.jpg",
        img3: "irene3.jpg",
        tix1: "P1000",
    },


    {   id: 10,
        name: "Kang Seul-gi",
        stage: "SEULGI",
        position: "Lead Vocalist, Main Dancer",
        bday: "February 10, 1994",
        nationality: "Korean",
        height: "1.61 m (5'2)",
        zodiac: "Aquarius ♒︎",
        img: "seulgi1.jpg",
        img2: "seulgi2.jpg",
        img3: "seulgi3.jpg",
        tix1: "P1000",
    },


    {   id: 21,
        name: "Son Seung-wan",
        stage: "WENDY",
        position: "Main Vocalist",
        bday: "February 21, 1994",
        nationality: "Korean",
        height: "1.59 m (5'2)",
        zodiac: "Pisces ♓︎",
        img: "wendy1.jpg",
        img2: "wendy2.jpg",
        img3: "wendy3.jpg",
        tix1: "P1000",
    },


    {   id: 3,
        name: "Park Soo-young",
        stage: "JOY",
        position: "Lead Rapper, Vocalist",
        bday: "September 3, 1996",
        nationality: "Korean",
        height: "1.68 m (5'6)",
        zodiac: "Virgo ♍︎",
        img: "joy1.jpg",
        img2: "joy2.jpg",
        img3: "joy3.jpg",
        tix1: "P1000", 
    },


    {   id: 5,
        name: "Kim Ye-rim",
        stage: "YERI",
        position: "Vocalist, Rapper, Maknae",
        bday: "March 5, 1999",
        nationality: "Korean",
        height: "1.58 m (5'1)",
        zodiac: "Pisces ♓︎",
        img: "yeri1.jpg",
        img2: "yeri2.jpg",
        img3: "yeri3.jpg",
        tix1: "P1000",
    },
   
]